mywork_1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
from django.views.generic import RedirectView


urlpatterns = [
    # 在urls.py文件中定义一个重定向的URL模式，
    # 将默认的URL模式重定向到login页面。
    path('', RedirectView.as_view(url='/login/')),
    # 默认情况下，Django提供了一个基本的后台管理页面，
    # 允许管理数据库中的数据、添加、修改和删除对象等操作。
    path('admin/', admin.site.urls),
    # 登录
    path('login/', views.login),
    # 注册
    path('register/',views.register),
    # 管理员登陆成功后进入主页
    path('admin_show/', views.admin_show),
    # 用户登陆成功后进入主页
    path('user_show/', views.user_show),
    # 管理员逐条添加数据
    path('admin_add/', views.admin_add),
    # 管理员批量上传数据
    path('admin_upload/', views.admin_upload),
    # 后台将批量上传的数据进行处理
    path('admin_multi/', views.admin_multi),
    # 上传失败报错并重新上传或上传成功继续上传
    path('admin_multi/admin_upload', views.admin_upload),
    # 上传成功返回主页
    path('admin_multi/admin_show', views.admin_show),
    # 管理员对某条数据进行编辑
    path('admin_edit/<int:id>/', views.admin_edit),
    # 管理员对某条数据进行删除
    path('admin_delete/<int:id>/', views.admin_delete),
    # 查看信息可视化大屏
    path('user_display/', views.user_display),
    # 查看信息分析图表
    path('user_charts/', views.user_charts),
    # 管理员对用户以及其他管理员信息进行管理
    path('admin_list/', views.admin_list),
    # 管理员添加其他用户或管理员
    path('admin_add_user/', views.admin_add_user),
    # 管理员编辑用户或管理员信息
    path('admin_edit_user/<int:id>/', views.admin_edit_user),
    # 管理员删除用户或管理员信息
    path('admin_delete_user/<int:id>/', views.admin_delete_user),
    # 将参数city传给数据处理函数进行图表数据生成
    path('api_data/', views.api_data),
    # 信息可视化大屏跳转到“分析结果”
    path('display_1/', views.display_1),
    # 信息可视化大屏跳转到“文本分类”
    path('display_2/', views.display_2),
    # 信息可视化大屏跳转到“回归预测”
    path('display_3/', views.display_3),
]

app1/models.py
from django.db import models


class information(models.Model):
    # 反馈人	   城市	 标题	类型	 提交时间	  内容	 回复时间	  回复部门  回复内容  来源  阅读量
    # QueSub  City	Title  Class  Time	Content	 RepTime  RepDep   RepCon  URL  reading
    QueSub = models.CharField('反馈人', max_length=50, default='匿名用户')
    City = models.CharField('城市', max_length=50)
    Title = models.TextField('标题')
    Class = models.CharField('类型', max_length=50)
    Time = models.DateTimeField('提交时间')
    Content = models.TextField('内容')
    RepTime = models.DateTimeField('回复时间')
    RepDep = models.CharField('回复部门', max_length=50)
    RepCon = models.TextField('回复内容')
    URL = models.CharField('来源', max_length=100)
    reading = models.IntegerField('阅读量', default=0)


class user(models.Model):
    name = models.CharField(verbose_name="账号名", max_length=30)
    password = models.CharField(verbose_name="密码", max_length=30)
    root_choice = (
        (1,"管理员"),
        (2,"普通用户")
    )
    root = models.SmallIntegerField(verbose_name="身份",choices=root_choice)

templates/admin_add.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建政务服务信息 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>反馈人（必填）</label>
                        <input type="text" class="form-control" placeholder="反馈人" name="QueSub"/>
                    </div>
                    <div class="form-group">
                        <label>选择城市（必填）</label>
                        <select class="form-control" name="City">
                            <option value="">点击选择</option>
                            <option value="赣州市">赣州市</option>
                            <option value="贵港市">贵港市</option>
                            <option value="惠州市">惠州市</option>
                            <option value="济宁市">济宁市</option>
                            <option value="泸州市">泸州市</option>
                            <option value="南阳市">南阳市</option>
                            <option value="内江市">内江市</option>
                            <option value="十堰市">十堰市</option>
                            <option value="温州市">温州市</option>
                            <option value="永州市">永州市</option>
                            <option value="肇庆市">肇庆市</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>标题（必填）</label>
                        <input type="text" class="form-control" placeholder="标题" name="Title"/>
                    </div>
                    <div class="form-group">
                        <label>类型（必填）</label>
                        <select class="form-control" name="Class">
                            <option value="">点击选择</option>
                            <option value="赣州市">投诉</option>
                            <option value="贵港市">咨询</option>
                            <option value="贵港市">建议</option>
                        </select>
                    </div>
                    <div class="layui-col-md6">
                        <label>选择日期（点击选择）</label><br>
                        <!--<input type="datetime-local" class="form-control" placeholder="日期" name="Time"/>-->
                        <div class="layui-input-inline" style="margin-top: 0.3em;">
                            <input type="text" id="begin_date" name="Time" placeholder="提问日期" class="layui-input"
                                   style="width: 200px; height:30px; font-size: 11px ">
                        </div>
                        <div class="layui-input-inline" style="margin-top:0.3em;">
                            <input type="text" id="end_date" name="RepTime" placeholder="回复日期" class="layui-input"
                                   style=" width: 200px; height: 30px; font-size: 11px ">
                        </div>
                    </div>
                    <!-- 初始化日期选择器的JavaScript代码 -->
                    <script>
                        layui.use('laydate', function () {
                            var laydate = layui.laydate;
                            var now = new Date(); // 获取当前时间
                            var nowStr = now.getFullYear() + '-' + (now.getMonth() + 1) + '-' + now.getDate(); // 格式化日期
                            // 初始化开始日期选择器
                            laydate.render({
                                elem: '#begin_date',
                                format: 'yyyy-MM-dd', // 日期格式
                                value: nowStr, // 设定初始值
                                trigger: 'click', // 点击触发选择器
                                done: function (value) {
                                    // 选择后的回调函数
                                    console.log(value);
                                }
                            });
                            // 初始化结束日期选择器
                            laydate.render({
                                elem: '#end_date',
                                format: 'yyyy-MM-dd', // 日期格式
                                value: nowStr, // 设定初始值
                                trigger: 'click', // 点击触发选择器
                                done: function (value) {
                                    // 选择后的回调函数
                                    console.log(value);
                                }
                            });
                        });
                    </script>
                    <br><br><br><br>
                    <div class="form-group">
                        <label>内容（必填）</label><br>
                        <textarea name="Content" rows="4" cols="90"></textarea>
                    </div>
                    <div class="form-group">
                        <label>回复部门</label>
                        <input type="text" class="form-control" placeholder="相关单位" name="RepDep"/>
                    </div>
                    <div class="form-group">
                        <label>回复内容</label><br>
                        <textarea name="RepCon" rows="4" cols="90"></textarea>
                    </div>
                    <div class="form-group">
                        <label>相关链接（必填）</label>
                        <input type="url" class="form-control" placeholder="URL" name="URL"/>
                    </div>
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin_edit.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 修改政务服务信息 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>反馈人</label>
                        <input type="text" class="form-control" placeholder="反馈人" name="QueSub" value="{{ obj.QueSub }}"/>
                    </div>
                    <div class="form-group">
                        <label>选择城市</label>
                        <select class="form-control" name="City">
                            <option value="">点击选择</option>
                            <option value="赣州市">赣州市</option>
                            <option value="贵港市">贵港市</option>
                            <option value="惠州市">惠州市</option>
                            <option value="济宁市">济宁市</option>
                            <option value="泸州市">泸州市</option>
                            <option value="南阳市">南阳市</option>
                            <option value="内江市">内江市</option>
                            <option value="十堰市">十堰市</option>
                            <option value="温州市">温州市</option>
                            <option value="永州市">永州市</option>
                            <option value="肇庆市">肇庆市</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="Title" value="{{ obj.Title }}"/>
                    </div>
                    <div class="form-group">
                        <label>类型</label>
                        <select class="form-control" name="Class">
                            <option value="">点击选择</option>
                            <option value="赣州市">投诉</option>
                            <option value="贵港市">咨询</option>
                            <option value="贵港市">建议</option>
                        </select>
                    </div>
                    <div class="layui-col-md6">
                        <label>选择日期</label>
                        <!--<input type="datetime-local" class="form-control" placeholder="日期" name="Time"/>-->
                        <div class="layui-input-inline" style="margin-top: 0.3em;">
                            <input type="text" id="begin_date" name="Time" placeholder="提问日期" class="layui-input"
                                   style="width: 200px; height:30px; font-size: 11px " value="{{ obj.Time }}">
                        </div>
                        <div class="layui-input-inline" style="margin-top:0.3em;">
                            <input type="text" id="end_date" name="RepTime" placeholder="回复日期" class="layui-input"
                                   style=" width: 200px; height: 30px; font-size: 11px " value="{{ obj.RepTime }}">
                        </div>
                    </div>
                    <!-- 初始化日期选择器的JavaScript代码 -->
                    <script>
                        layui.use('laydate', function () {
                            var laydate = layui.laydate;
                            // 初始化开始日期选择器
                            laydate.render({
                                elem: '#begin_date',
                                format: 'yyyy-MM-dd', // 日期格式
                                trigger: 'click', // 点击触发选择器
                                done: function (value) {
                                    // 选择后的回调函数
                                    console.log(value);
                                }
                            });
                            // 初始化结束日期选择器
                            laydate.render({
                                elem: '#end_date',
                                format: 'yyyy-MM-dd', // 日期格式
                                trigger: 'click', // 点击触发选择器
                                done: function (value) {
                                    // 选择后的回调函数
                                    console.log(value);
                                }
                            });
                        });
                    </script>
                    <br><br><br>
                    <div class="form-group">
                        <label>内容</label><br>
                        <textarea name="Content" rows="4" cols="90">{{ obj.Content }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>回复部门</label>
                        <input type="text" class="form-control" placeholder="相关单位" name="RepDep" value="{{ obj.RepDep }}"/>
                    </div>
                    <div class="form-group">
                        <label>回复内容</label><br>
                        <textarea name="RepCon" rows="4" cols="90">{{ obj.RepCon }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>相关链接</label>
                        <input type="url" class="form-control" placeholder="URL" name="URL" value="{{ obj.URL }}"/>
                    </div>
                    <div class="form-group">
                        <label>阅读量</label>
                        <input type="number" min="0" max="10" step="1" name="reading" value="{{ obj.reading }}"/>
                    </div>
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin_edit_user.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 修改用户信息 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin_show/"> 政务服务信息管理系统 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/admin_list/" target="_blank">用户信息管理</a></li>
                <li><a href="/user_display/" target="_blank">信息展示</a></li>
                <li><a href="/user_charts/" target="_blank">信息图表</a></li>
                <!--<li><a href="/display_1/" target="_blank">分析结果</a></li>-->
                <li><a href="/display_2/" target="_blank">文本分类</a></li>
                <li><a href="/display_3/" target="_blank">回归预测</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">登录成功（管理员） <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/login/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div>
    {% block content %}{% endblock %}
</div>
{% block js %}{% endblock %}
</body>

<footer>
    <div class="container-fluid" style="padding-top: 40px;">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="jumbotron">
                <div class="container">
                    <center>
                        <p>Copyright [2023] by [SongHuawei] </p>
                        <p><a href="http://xxxy.lzu.edu.cn/" target="_blank">兰州大学信息科学与工程学院</a></p>
                        <p><a href="https://github.com/SongHuawei" target="_blank">我的GitHub</a></p>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>
</footer>
</html>

templates/admin_list.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/admin_add_user/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户信息管理
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>账号</th>
                    <th>身份</th>
                    <th>密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.get_root_display }}</td>
                        <td>************</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin_edit_user/{{ obj.id }}/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin_delete_user/{{ obj.id }}/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/admin_show.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px; height: 40px">
            <a class="btn btn-success" href="/admin_add/" target="_blank">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建政务服务信息
            </a>
            <a class="btn btn-info" href="/admin_upload/" target="_blank">
                <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                批量上传信息
            </a>
        </div>
        <div style="margin-bottom: 10px; height: 40px">
            <form method="get" class="form-inline">
                <div style="float:left; width: 150px">
                    <div class="form-group">
                        <select class="form-control" name="c">
                            <option value="">请选择城市</option>
                            <option value="赣州市">赣州市</option>
                            <option value="贵港市">贵港市</option>
                            <option value="惠州市">惠州市</option>
                            <option value="济宁市">济宁市</option>
                            <option value="泸州市">泸州市</option>
                            <option value="南阳市">南阳市</option>
                            <option value="内江市">内江市</option>
                            <option value="十堰市">十堰市</option>
                            <option value="温州市">温州市</option>
                            <option value="永州市">永州市</option>
                            <option value="肇庆市">肇庆市</option>
                        </select>
                    </div>
                </div>
                <div style="float:left;width: 230px">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="输入标题关键字....">
                    </div>
                </div>
                <div style="float:left">
                    <div class="input-group">
                        <button class="btn btn-default" type="submit">搜索</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                问政信息列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>所在市</th>
                    <th>内容</th>
                    <th>相关单位</th>
                    <th>链接</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th style="width: 10%">{{ obj.City }}</th>
                        <td style="width: 55%">{{ obj.Title }}</td>
                        <td style="width: 15%">{{ obj.RepDep }}</td>
                        <td style="width: 10%"><a class="btn btn" href="{{ obj.URL }}" target="_blank">点击跳转</a></td>
                        <td style="width: 10%">
                            <a class="btn btn-primary btn-xs" href="/admin_edit/{{ obj.id }}/" target="_blank">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin_delete/{{ obj.id }}/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container">
            <nav aria-label="...">
                <ul class="pagination">
                    {{ page_string }}
                    <li>
                        <form style="float: left;margin-right: 10px" method="get">
                            <input type="text" style="position:relative;float:left;display:inline-block;width: 100px"
                                   name="page" class="form-control" placeholder="页码">
                            <span>
                        <button class="btn btn-primary" type="submit">跳转</button>
                    </span>
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/admin_upload.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 问政信息批量上传 </h3>
            </div>
            <form method="post" enctype="multipart/form-data" action="/admin_multi/">
                {% csrf_token %}
                <div class="container">
                    <div class="form-group">
                        <br><label>点击下方按钮上传文件</label><br><br>
                        <input type="file" name="upload" id="exampleInputFile"><br>
                        <p class="help-block">
                            请上传符合要求的excel文件：请注意时间格式为yyyy-mm-dd hh:mm:ss
                        </p><br>
                        <input type="submit" value="上传" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }
        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>

<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post">
        {% csrf_token %}
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">用户名</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="name" placeholder="用户名">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="密码">
            </div>
            <span style="color:red">{{ field }}</span>
            <input type="submit" value="登 录" class="btn btn-primary">
            <a class="btn btn-default" href="/register" target="_blank" style="float: right">注 册</a>
        </form>
    </form>
</div>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }
        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>

<body>
<div class="account">
    <h2>用户注册</h2>
    <form method="post">
        {% csrf_token %}
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">用户名</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="name" placeholder="用户名">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="密码">
            </div>
            <span style="color:red">{{ field }}</span>
            <input type="submit" value="提 交" class="btn btn-primary">
        </form>
    </form>
</div>
</body>
</html>

templates/user_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
    <style>
        .navbar {
            border-radius: 0;
        }

        .overflow {
            max-width: 100px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .overflow:hover {
            white-space: normal;
            overflow: visible;
            text-overflow: initial;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/user_show/"> 政务服务信息查询系统 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/user_display/" target="_blank">信息展示</a></li>
                <li><a href="/user_charts/" target="_blank">信息图表</a></li>
                <!--<li><a href="/display_1/" target="_blank">分析结果</a></li>-->
                <li><a href="/display_2/" target="_blank">文本分类</a></li>
                <li><a href="/display_3/" target="_blank">回归预测</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">登录成功（普通用户） <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/login/">退出登陆</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div>
    {% block content %}{% endblock %}
</div>
{% block js %}{% endblock %}
</body>

<footer>
    <div class="container-fluid" style="padding-top: 40px;">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div class="jumbotron">
                    <div class="container">
                        <center>
                            <p>Copyright [2023] by [SongHuawei] </p>
                            <p><a href="http://xxxy.lzu.edu.cn/" target="_blank">兰州大学信息科学与工程学院</a></p>
                            <p><a href="https://github.com/SongHuawei" target="_blank">我的GitHub</a></p>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</html>